title: title - the Simplex theme
logo_img: /assets/img/icons/autoaudit.png
favicon: /assets/temp.ico
description: Have a nice day!!
global_tags: global tags TomymoT
copyright: © TommyyymmoT 2023

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
