title: Current nothing here
logo_img: /assets/img/icons/Fujiwara_Chika_small.svg
favicon: /assets/temp.ico
description: Have a nice day!!
global_tags: global tags TomymoT
copyright: © TommyyymmoT 2025

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
